name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - run: nix -vL flake check

      - run: nix -vL build

      - uses: actions/upload-artifact@v4
        with:
          name: zmk_firmware
          path: result
